### ISSUE TITLE
Atualizar endpoints API do microserviço IGDBService

### ISSUE THREAD

**Issue by BRZangado** [fga-eps-mds/2018.2-GamesBI#105]
## Description
Para cada endpoint os dados que serão recuperados precisam ser relevantes para aquela chamada.

## Tasks
- [ ] Endpoint Steam: Retornar apenas jogos que tenham id na steam
- [ ] Endpoint Name: Retornar apenas os nomes dos jogos salvos
- [ ] Endpoint All: Aplicar paginação.

## Acceptance criteria
Endpoints retornando corretamente apenas os atributos estipulados

## How this will benefit the project?
Maior facilidade no uso da API
