### ISSUE TITLE
TS07 Criar models que comportam multiplos modelos

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#120]
## Tasks
- [ ] Model de jogos
- [ ] Model de genero
- [ ] Model de stream
- [ ] Model de usuário

## Acceptance criteria

Deve seguir a especificação do documento de arquitetura.

## How this will benefit the project?
Possibilita o crossdata a armazenar os dados dos multiplos serviços

**Comment by BRZangado** [comment]
Todos os "ids" na model Game estão com primary_key=True. Retirar

**Comment by BRZangado** [comment]
Inverter relação entre Game e Stream
