### ISSUE TITLE
Criar shellscript/makefile

### ISSUE THREAD

**Issue by BRZangado** [fga-eps-mds/2018.2-GamesBI#125]
## Description
Criar shellscript ou makefile para comandos digitados com frequência

## Tasks
- [ ] Implementar no repo IGDBService
- [ ] Implementar no repo SteamService
- [ ] Implementar no repo YoutubeService
- [ ] Implementar no repo TwitchService

## How this will benefit the project?
Agilizar processos
