### ISSUE TITLE
Adicionar teste para cubrir APIs

### ISSUE THREAD

**Issue by BRZangado** [fga-eps-mds/2018.2-GamesBI#134]
## Description
Adicionar testes para cubir endpoints das API's

## Tasks
- [x] Testes API Twitch
- [x] Testes API Youtube
- [x] Testes API Steam

## Acceptance criteria
Cobrir todos os endpoints

## How this will benefit the project?
Verificar funcionamento correto das APIs e aumentar cobertura de código

**Comment by BRZangado** [comment]
@lmmLucasMachado Cadê os mocks?
