### ISSUE TITLE
Realizar deploy das API's

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#157]
## Description

Não há servidor de homologação nem de produção em nenhum repositório.

## Tasks
- [x] Definir qual servidor utilizar
- [x] Realizar o deploy dos importadores
- [ ] Realizar o deploy do cross-data
- [x] Realizar o deploy do front-end

## Acceptance criteria

Deploy automático integrado com o travis em cada repositório

## How this will benefit the project?
Servidor de homologação e de produção de cada serviço
