### ISSUE TITLE
Atualizar sprints

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GamesBI#183]
## Description

As sprints estão com poucas informações
## Tasks
- [x] Decisões tomadas
- [x] Objetivos das sprints
- [x] Feedback
- [x] Sprint 5 planning
- [x] Métricas de código
- [x] Quadro de conhecimento da sprint 06

## Acceptance criteria

Toda documentação deve estar disponivel no github

## How this will benefit the project?
Melhora a documentação do desenvolvimento

**Comment by ingrdst** [comment]
@arthurarp colocar quadro de conhecimento no planejamento da sprint 06 no local especificado em: sprints/sprint6planning.html
