### ISSUE TITLE
Documentar as daily meetings

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#38]
## Issue Title
Documentar as daily meetings

## Description

Tem que documentar elas para ter evidência da ocorrência delas

## Tasks
- [x] Criar template para a documentação
- [x] Documentar as dailies que já ocorreram

## Acceptance criteria

Evidências dessa documentação dentro da wiki do projeto

## How this will benefit the project?
Projeto mais documentado

**Comment by nukdown** [comment]
- [ ] Passar da wiki para o githubpages

**Comment by nukdown** [comment]
Documentação das sprints atualizada
https://fga-eps-mds.github.io/2018.2-GamesBI/sprint.html
