### ISSUE TITLE
Levantar requisitos à partir das reuniões com o cliente

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#39]
## Issue Title
Levantar requisitos à partir das reuniões com o cliente

## Description

Criar um documento que esteja definidos os requisitos do projeto

## Tasks
- [ ] Revisar o áudio da reunião do dia 22/08
- [ ] Criação do documento
- [ ] Definição dos requisitos

## Acceptance criteria

Documento com os requisitos dentro da wiki deste repositório

## How this will benefit the project?
Mais documentação
