### ISSUE TITLE
Treinamento de documentação

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#40]
## Issue Title
Treinamento de documentação

## Description

Realizar treinamento de cada um dos documentos responsáveis pela equipe de desenvolvimento para a release 1

## Tasks
- [x] Documento de visão
- [x] Documento de arquitetura
- [x] Documento de Especificação Suplementar

## Acceptance criteria

Treinamento realizado com a equipe de MDS

## How this will benefit the project?
Documentação necessária para a release 1
