### ISSUE TITLE
Treinamento de Docker

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#47]
## Issue Title
Treinamento de Docker

## Description

Ensinar o grupo de mds sobre como utilizar o docker durante o desenvolvimento do projeto

## Tasks
- [x] instalação do docker
- [x] instalação do docker-compose
- [x] containers
- [x] execução de comandos dentro do container

## Acceptance criteria

Realizar o treinamento

## How this will benefit the project?
Entender o uso do docker durante o desenvolvimento
