### ISSUE TITLE
Arrumar o front do githhub pages

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#57]
## Issue Title
Arrumar o front do githhub pages

## Description

Deixar o front de acordo com a discplina, criando abas e página relevantes

## Tasks
- [x] Aba para arquivos de desenvolvimento
- [x] Aba para arquivos de planejamento
- [x] Aba de Roadmaps
- [x] Aba de sprints

## Acceptance criteria

Página do github.io contendo todas essas abas funcionando corretamente

## How this will benefit the project?
Melhor visualização da documentação
