### ISSUE TITLE
Criar Estrutura Analítica do Projeto

### ISSUE THREAD

**Issue by augustovilarins** [fga-eps-mds/2018.2-GamesBI#71]
## Description

Construir em conjunto com a equipe a EAP do projeto.

## Tasks
- [x] Reunir com a equipe
- [x] Criar o documento
- [x] Criar diagrama de causa e efeito
- [x] Validar com o cliente

## Acceptance criteria

Evidências da eap na página de documentação do projeto

Validar com

## How this will benefit the project?
Melhorar a documentação do projeto
