### ISSUE TITLE
Implementar o pipeline de devops nos outros repositórios

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GamesBI#75]
## Issue Title
Implementar o pipeline de devops nos outros repositórios

## Description

Implementar todo o pipeline nos demais repositórios do projeto

## Tasks
- [x] Repositório da Steam
- [x] Repositório da Twitch
- [x] Repositório do Youtube
- [x] Repositório do IGDB

## Acceptance criteria

Evidências do pipeline em cada um dos repositórios

## How this will benefit the project?
Pipline de devops implementado
